-file("/usr/local/Cellar/erlang/21.0.1/lib/erlang/lib/parsetools-2.1.7/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lucene_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 73).

%% Strip the first and last char, which will be quotes. Unescape anything else.
strip(S) ->
    lists:sublist(S, 2, length(S) - 2).

%% Unescape any escaped chars *except* for '*' and '?'.
unescape(S) ->
    unescape(S, []).
unescape([$\\,C|Rest], Acc) when C/=$* andalso C/=$? ->
    unescape(Rest, [C|Acc]);
unescape([C|Rest], Acc) ->
    unescape(Rest, [C|Acc]);
unescape([], Acc) ->
    lists:reverse(Acc).

%% Convert a fuzzy match to float. We know first char is ~.
fuzzy_to_float(S) ->
    list_to_float(tl(S)).

%% Convert a proximity search to integer. We know first char is ~.
proximity_to_integer(S) ->
    list_to_integer(tl(S)).

%% Convert a search boost to integer. We know first char is ^.
boost1_to_float(S) ->
    float(list_to_integer(tl(S))).

boost2_to_float(S) ->
    list_to_float(tl(S)).

-file("/usr/local/Cellar/erlang/21.0.1/lib/erlang/lib/parsetools-2.1.7/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.erl", 336).
yystate() -> 48.

yystate(51, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [82|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 81 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,51};
yystate(50, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,50};
yystate(49, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,49};
yystate(48, [126|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [125|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [124|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [123|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [94|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [93|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [92|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [91|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [84|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [79|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [78|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [65|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [58|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [45|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [44|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [43|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [42|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [41|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [40|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [39|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [38|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [34|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [33|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [32|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [13|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [11|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [12|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [10|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(48, [9|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [8|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 46, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 90 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,48};
yystate(47, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 15, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(45, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [79|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 78 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,45};
yystate(44, [48|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 16, Tlen);
yystate(44, [49|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 16, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 50, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 16, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,44};
yystate(43, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [79|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 78 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,43};
yystate(42, [33|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 5, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,42};
yystate(41, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [84|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 83 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,41};
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 18, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(38, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line+1, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,37};
yystate(36, [46|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(40, Ics, Line, Tlen+1, 18, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,36};
yystate(35, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 25, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(33, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [78|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 42, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 77 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,33};
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 24, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,31};
yystate(30, [92|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, [34|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, [10|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line+1, Tlen+1, 23, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(38, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(38, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(38, Ics, Line, Tlen+1, 23, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,30};
yystate(29, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [68|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 67 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,29};
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 17, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,28};
yystate(27, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 26, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,27};
yystate(26, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line+1, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [93|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [94|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [92|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [91|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [63|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [58|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [42|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [34|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [33|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [32|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [13|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [11|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [12|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [9|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 37 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 38, C =< 41 ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 59, C =< 62 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 123, C =< 126 ->
    yystate(15, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(23, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(22, [92|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, [34|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, [10|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line+1, Tlen+1, 28, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(38, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(38, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(38, Ics, Line, Tlen+1, 28, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,22};
yystate(21, [58|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 6, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,21};
yystate(20, [124|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 3, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(18, [38|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,18};
yystate(17, [45|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 8, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(15, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line+1, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(14, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,14};
yystate(13, [43|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 19, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,12};
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(9, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(8, [46|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, 20, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, 28, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(50, Ics, Line, Tlen+1, 28, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,7};
yystate(6, [92|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [39|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [10|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line+1, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(14, Ics, Line, Tlen+1, 22, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,6};
yystate(5, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(2, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line+1, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(2, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [92|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [39|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [10|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line+1, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(14, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(14, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(14, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(14, Ics, Line, Tlen+1, 28, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,1};
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, 21, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, _, _, _) ->
    yyaction_27();
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 41).
yyaction_0(TokenChars, TokenLine) ->
     { token, { intersection, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 42).
yyaction_1(TokenChars, TokenLine) ->
     { token, { intersection, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 43).
yyaction_2(TokenChars, TokenLine) ->
     { token, { union, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 44).
yyaction_3(TokenChars, TokenLine) ->
     { token, { union, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 45).
yyaction_4(TokenChars, TokenLine) ->
     { token, { negation, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 46).
yyaction_5(TokenChars, TokenLine) ->
     { token, { negation, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 47).
yyaction_6(TokenChars, TokenLine) ->
     { token, { scope, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 48).
yyaction_7(TokenChars, TokenLine) ->
     { token, { required, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 49).
yyaction_8(TokenChars, TokenLine) ->
     { token, { prohibited, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 50).
yyaction_9(TokenChars, TokenLine) ->
     { token, { group_start, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 51).
yyaction_10(TokenChars, TokenLine) ->
     { token, { group_end, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 52).
yyaction_11(TokenChars, TokenLine) ->
     { token, { inclusive_start, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 53).
yyaction_12(TokenChars, TokenLine) ->
     { token, { inclusive_end, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 54).
yyaction_13(TokenChars, TokenLine) ->
     { token, { exclusive_start, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 55).
yyaction_14(TokenChars, TokenLine) ->
     { token, { exclusive_end, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 56).
yyaction_15(TokenChars, TokenLine) ->
     { token, { range_to, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/1}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 57).
yyaction_16(TokenLine) ->
     { token, { fuzzy, TokenLine, 0.5 } } .

-compile({inline,yyaction_17/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 58).
yyaction_17(TokenChars, TokenLine) ->
     { token, { fuzzy, TokenLine, fuzzy_to_float (TokenChars) } } .

-compile({inline,yyaction_18/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 59).
yyaction_18(TokenChars, TokenLine) ->
     { token, { proximity, TokenLine, proximity_to_integer (TokenChars) } } .

-compile({inline,yyaction_19/1}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 60).
yyaction_19(TokenLine) ->
     { token, { boost, TokenLine, 1.0 } } .

-compile({inline,yyaction_20/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 61).
yyaction_20(TokenChars, TokenLine) ->
     { token, { boost, TokenLine, boost1_to_float (TokenChars) } } .

-compile({inline,yyaction_21/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 62).
yyaction_21(TokenChars, TokenLine) ->
     { token, { boost, TokenLine, boost2_to_float (TokenChars) } } .

-compile({inline,yyaction_22/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 63).
yyaction_22(TokenChars, TokenLine) ->
     { token, { string, TokenLine, unescape (strip (TokenChars)) } } .

-compile({inline,yyaction_23/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 64).
yyaction_23(TokenChars, TokenLine) ->
     { token, { string, TokenLine, unescape (strip (TokenChars)) } } .

-compile({inline,yyaction_24/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 65).
yyaction_24(TokenChars, TokenLine) ->
     { token, { wildcard_char, TokenLine, unescape (TokenChars) } } .

-compile({inline,yyaction_25/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 66).
yyaction_25(TokenChars, TokenLine) ->
     { token, { wildcard_glob, TokenLine, unescape (TokenChars) } } .

-compile({inline,yyaction_26/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 67).
yyaction_26(TokenChars, TokenLine) ->
     { token, { string, TokenLine, unescape (TokenChars) } } .

-compile({inline,yyaction_27/0}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 68).
yyaction_27() ->
     skip_token .

-compile({inline,yyaction_28/2}).
-file("/Users/goncalotomas/git/lucene_parser/_build/test/lib/lucene_parser/src/lucene_scan.xrl", 69).
yyaction_28(TokenChars, TokenLine) ->
     { error, lists : flatten (io_lib : format ("invalid character \"~s\" at line ~p", [TokenChars, TokenLine ])) } .

-file("/usr/local/Cellar/erlang/21.0.1/lib/erlang/lib/parsetools-2.1.7/include/leexinc.hrl", 313).
